# Generated by Django 6.0.6 on 2026-06-08 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlists', to='groups.musicgroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scaletta',
                'verbose_name_plural': 'Scalette',
                'db_table': 'setlists_setlist',
                'ordering': ['-event_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SetlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('transposition', models.SmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='setlists.setlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_items', to='songs.song')),
            ],
            options={
                'verbose_name': 'Elemento scaletta',
                'verbose_name_plural': 'Elementi scaletta',
                'db_table': 'setlists_setlistitem',
                'ordering': ['order'],
                'unique_together': {('setlist', 'order')},
            },
        ),
    ]
