# Generated by Django 6.0.6 on 2026-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_guest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
