# Generated by Django 6.0.6 on 2026-06-08 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Riga testo',
                'verbose_name_plural': 'Righe testo',
                'db_table': 'songs_lyricline',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChordAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chord', models.CharField(max_length=20)),
                ('position', models.PositiveSmallIntegerField()),
                ('lyric_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chords', to='songs.lyricline')),
            ],
            options={
                'verbose_name': 'Accordo',
                'verbose_name_plural': 'Accordi',
                'db_table': 'songs_chordannotation',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('key', models.CharField(blank=True, choices=[('C', 'C'), ('C#', 'C#'), ('Db', 'Db'), ('D', 'D'), ('D#', 'D#'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('Gb', 'Gb'), ('G', 'G'), ('G#', 'G#'), ('Ab', 'Ab'), ('A', 'A'), ('A#', 'A#'), ('Bb', 'Bb'), ('B', 'B')], max_length=3)),
                ('mode', models.CharField(choices=[('major', 'Maggiore'), ('minor', 'Minore')], default='major', max_length=10)),
                ('bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canzone',
                'verbose_name_plural': 'Canzoni',
                'db_table': 'songs_song',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='lyricline',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_lines', to='songs.song'),
        ),
    ]
