# Generated by Django 6.0.6 on 2026-06-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_add_invite_token'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='extra_groups',
            field=models.ManyToManyField(blank=True, related_name='extra_songs', to='groups.musicgroup'),
        ),
        migrations.AddField(
            model_name='song',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='groups.musicgroup'),
        ),
    ]
