# Generated by Django 6.0.6 on 2026-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_add_group_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
