# Generated by Django 6.0.6 on 2026-06-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_add_song_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
