# Generated by Django 6.0.6 on 2026-06-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_add_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genere musicale',
                'verbose_name_plural': 'Generi musicali',
                'db_table': 'songs_genre',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='chords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='song',
            name='genre_custom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.genre'),
        ),
    ]
